<a href="https://colab.research.google.com/github/RenukaBenkalkar/Python/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Create 1D array of numbers from 10 to 50 inclusive
import numpy as np
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [2]:
# 2D array of shape (3,3) with values from 1 to 9
import numpy as np
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#2.Indexing and slicing
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#Extract first five elements
print(arr[0:6])

#Extract every alternate element starting from index 1
print(arr[1::2])

#Reverse the array using slicing
print(arr[::-1])

In [ ]:
#3. Matrix operation
import numpy as np
arr_rand1 = np.random.randint(1,20,size=(3,3))

arr_rand2 = np.random.randint(1,20,size=(3,3))

#sum of 2 matrix
sum = arr_rand1 + arr_rand2
#print(sum)

#product of 2 matrix
product = arr_rand1 * arr_rand2
print(product)

#matrix multipication
result = np.dot(arr_rand1,arr_rand2)
print(result)

In [ ]:
#4. Broadcasting  refers to the ability of performing operations on arrays with different shapes
import numpy as np
A = np.array([[1], [2], [3]])
B = np.array([4, 5, 6])
result = A + B
print(result)


In [5]:
#5.Statistic Computing
import numpy as np
scores = np.array([65,78,90,55,88,92,75,80])
print("Mean is ", np.mean(scores))
print("Median is ", np.median(scores))
print("Standard Deviation is ", np.std(scores))
print("Min Score is ", np.min(scores))
print("Max Score is ", np.max(scores))


Mean is  77.875
Median is  79.0
Standard Deviation is  11.994139193789607
Min Score is  55
Max Score is  92
