<a href="https://colab.research.google.com/github/RenukaBenkalkar/Python/blob/main/Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Sampling Technique
import pandas as pd
flight ={
    'CustomerName':['John','Lisa','Sara','Kiara'],
    'SeatNumber':[20,21,22,23],
    'NumOfFamilyMembers':[2,3,4,3]
}

d=pd.DataFrame(flight)
print(d)
#sampling
d.sample(2)

  CustomerName  SeatNumber  NumOfFamilyMembers
0         John          20                   2
1         Lisa          21                   3
2         Sara          22                   4
3        Kiara          23                   3


CustomerName  SeatNumber  NumOfFamilyMembers
2         Sara          22                   4
0         John          20                   2

In [ ]:
#Stratified sampling
import pandas as pd
sport={
    'PersonName':['Sachin','yuvraj','kapil','Joy','John','Kavin'],
    'Category':['cricket','Cricket','Football','Tennis','Tennis','Football'],
    'CashAwards':[2000,3000,5000,7000,8000,9000]
}
df=pd.DataFrame(sport)
print(d)
df.groupby('Category').apply(lambda x:x.sample(1))


  PersonName  Category  CashAwards
0     Sachin   cricket        2000
1     yuvraj   Cricket        3000
2      kapil  Football        5000
3        Joy    Tennis        7000
4       John    Tennis        8000
5      Kavin  Football        9000


<ipython-input-12-082d773c17db>:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('Category').apply(lambda x:x.sample(1))


PersonName  Category  CashAwards
Category                                   
Cricket  1     yuvraj   Cricket        3000
Football 2      kapil  Football        5000
Tennis   3        Joy    Tennis        7000
cricket  0     Sachin   cricket        2000

In [ ]:
#Get marks and Display grades
marks =int(input('Enter the Marks '))
if marks>=90 and marks<=100:
  print('Grade points 10: ' +  'outstanding')
elif marks>=80 and marks<90:
  print('Grade points 9: ' + 'Exellent')
elif marks>=70 and marks<80:
  print('Grade points 8: ' + 'Very Good')
elif(marks>=60) and marks<70:
  print('Grade points 7: ' +'Good')
elif(marks>=50) and marks<60:
  print('Grade points 6: ' +'Above Average')
elif(marks>=40) and marks<50:
  print('Grade points 5: ' +'Average')
elif(marks>=30) and marks<40:
  print('Grade points 4: ' +'Pass')
elif(marks>=0) and marks<30:
  print('Grade points 0: ' +'Fail')
else:
  print('Enter valid Number')


Enter the Marks 57
Grade points 6: Above Average


In [ ]:
#BMI Calculater
weight=float(input('Please Enter weight in kg '))
height=float(input('Please Enter Height in meters '))
bmi = (weight)/(height**2)
print('Your BMI is ',bmi)
if bmi<=18.4:
  print('Underweight')
elif bmi>=18.5 and bmi <=24.9:
  print('Normal')
elif bmi>=25 and bmi<=39.9:
  print('Overweight')
elif bmi>=40.0:
  print('obese')
else:
  print('Enter valid Weight and Height')



Please Enter weight in kg 50
Please Enter Height in meters 1.56
Your BMI is  20.5456936226167
Normal


In [ ]:
#multiplication table
num=int(input('Enter the Number:'))
multiply=0
for i in range(1,11):
   multiply = num * i
   print(num,'x',i, '=',multiply)

Enter the Number:9
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


In [ ]:
#Student Registration Number using While Loop
n=int(input('Enter number of students'))
reg=5000
i=0
while(i<n):
  name = input('your good name.')
  print('Hello ',name, 'Congrate welcome to ABC university')
  i=i+1
  print('Your Registration number is',reg )
  reg=reg+1
  print('\n')
else:
   print('sorry Admission over ')

Enter number of students2
your good name.aaaa
Hello  aaaa Congrate welcome to ABC university
Your Registration number is 5000


your good name.cccc
Hello  cccc Congrate welcome to ABC university
Your Registration number is 5001


sorry Admission over 


In [ ]:
#Create Dictionary using 4 country data
country={
    'CountryName':['United Kingdom','India','France','Spain'],
    'Population':['68.3 million','1.45 billion','68.4 million','49.1 milion'],
    'Area':['607 square miles','1,269,219 square miles','248,573 square miles','195,360 square miles'],
    'Capital':['London','New Delhi','Paris','Madrid']
}

country


{'CountryName': ['United Kingdom', 'India', 'France', 'Spain'],
 'Population': ['68.3 million', '1.45 billion', '68.4 million', '49.1 milion'],
 'Area': ['607 square miles',
  '1,269,219 square miles',
  '248,573 square miles',
  '195,360 square miles'],
 'Capital': ['London', 'New Delhi', 'Paris', 'Madrid']}

In [ ]:
#Find total price of all products in product dictionary
products={
    'ID' :[100,101,102],
    'Name':['laptop','iphone','tab'],
    'Price':[1200,500,700]
}
#products['Price']
sum=0
for i in products['Price']:
  sum=sum+i
  print(i)
print(sum)


1200
500
700
2400


In [ ]:
#Find the count of products in product dictionary
products={
    'ID' :[100,101,102],
    'Name':['laptop','iphone','tab'],
    'Price':[1200,500,700]
}
count=0
for i in products['ID']:
  count=count+1
print(count)

3


In [ ]:
#Design calculater- add, sub,mul,div using function
ch=int(input('Enter your choice , 1 to add, 2 to sub, 3 to mul, 4 to div : '))
a=int(input('Enter first number '))
b=int(input('Enter second number '))
def add(a,b):
  return a+b
def sub(a,b):
  return a-b
def mul(a,b):
  return a*b
def div(a,b):
  return a/b

if ch==1:
  print('Addition ',add(a,b))
elif ch==2:
    print('Subtraction ',sub(a,b))
elif ch==3:
   print('multiplication ',mul(a,b))
elif ch==4:
   print('Division ',div(a,b))
else:
   print('Invalid choice')



Enter your choice , 1 to add, 2 to sub, 3 to mul, 4 to div :2
Enter first number 10
Enter second number 5
Subtraction  5


In [ ]:
import numpy as np
#convert to boolean
arr = np.array([1,0,12,45])
arrb =arr.astype(bool)
print(arrb)

[ True False  True  True]


Numpy Assignment


In [1]:
# Create 1D array of numbers from 10 to 50 inclusive
import numpy as np
arr = np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [3]:
# 2D array of shape (3,3) with values from 1 to 9
import numpy as np
arr = np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#2.Indexing and slicing
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#Extract first five elements
print(arr[0:6])

#Extract every alternate element starting from index 1
print(arr[1::2])

#Reverse the array using slicing
print(arr[::-1])

[10 20 30 40 50 60]
[20 40 60 80]
[90 80 70 60 50 40 30 20 10]


In [21]:
#3. Matrix operation
import numpy as np
arr_rand1 = np.random.randint(1,20,size=(3,3))

arr_rand2 = np.random.randint(1,20,size=(3,3))

#sum of 2 matrix
sum = arr_rand1 + arr_rand2
#print(sum)

#product of 2 matrix
product = arr_rand1 * arr_rand2
print(product)

#matrix multipication
result = np.dot(arr_rand1,arr_rand2)
print(result)


[[ 70 209 176]
 [ 90 238  12]
 [180  60  27]]
[[420 500 259]
 [255 357 162]
 [300 411 261]]


In [22]:
#4. Broadcasting
import numpy as np
A = np.array([[1], [2], [3]])
B = np.array([4, 5, 6])
result = A + B
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [24]:
#5.Statistic Computing
import numpy as np
scores = np.array([65,78,90,55,88,92,75,80])
print(np.mean(scores))
print(np.median(scores))
print(np.std(scores))
print(np.min(scores))
print(np.max(scores))


77.875
79.0
11.994139193789607
55
92
